name: sqflite_migration
description: A library to enable sqlite db migrations, using sqflite plugin.
version: 0.0.2
author: Efthymios Sarmpanis <e.sarbanis@gmail.com>
homepage: https://github.com/flutterings/sqflite_migration

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  matcher: ^0.12.3+1

flutter:
